# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import my_pb2 as my__pb2


class FileTransferServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Case1 = channel.unary_unary(
                '/proto15test.FileTransferService/Case1',
                request_serializer=my__pb2.FileRequest.SerializeToString,
                response_deserializer=my__pb2.FileResponse.FromString,
                )
        self.Case2 = channel.stream_unary(
                '/proto15test.FileTransferService/Case2',
                request_serializer=my__pb2.FileRequest.SerializeToString,
                response_deserializer=my__pb2.FileResponse.FromString,
                )
        self.Case3 = channel.unary_stream(
                '/proto15test.FileTransferService/Case3',
                request_serializer=my__pb2.FileRequest.SerializeToString,
                response_deserializer=my__pb2.FileResponse.FromString,
                )
        self.Case4 = channel.stream_stream(
                '/proto15test.FileTransferService/Case4',
                request_serializer=my__pb2.FileRequest.SerializeToString,
                response_deserializer=my__pb2.FileResponse.FromString,
                )


class FileTransferServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Case1(self, request, context):
        """Способ 1: Унарная передача - клиент отправляет запрос, сервер отвечает одним ответом
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Case2(self, request_iterator, context):
        """Способ 2: Потоковая передача с клиента на сервер - клиент отправляет поток запросов, сервер отвечает ответом
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Case3(self, request, context):
        """Способ 3: Потоковая передача с клиента на сервер - клиент отправляет запрос, сервер отвечает потоком ответов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Case4(self, request_iterator, context):
        """Способ 4: Двунаправленная потоковая передача - клиент и сервер обмениваются потоками запросов и ответов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileTransferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Case1': grpc.unary_unary_rpc_method_handler(
                    servicer.Case1,
                    request_deserializer=my__pb2.FileRequest.FromString,
                    response_serializer=my__pb2.FileResponse.SerializeToString,
            ),
            'Case2': grpc.stream_unary_rpc_method_handler(
                    servicer.Case2,
                    request_deserializer=my__pb2.FileRequest.FromString,
                    response_serializer=my__pb2.FileResponse.SerializeToString,
            ),
            'Case3': grpc.unary_stream_rpc_method_handler(
                    servicer.Case3,
                    request_deserializer=my__pb2.FileRequest.FromString,
                    response_serializer=my__pb2.FileResponse.SerializeToString,
            ),
            'Case4': grpc.stream_stream_rpc_method_handler(
                    servicer.Case4,
                    request_deserializer=my__pb2.FileRequest.FromString,
                    response_serializer=my__pb2.FileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto15test.FileTransferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileTransferService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Case1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto15test.FileTransferService/Case1',
            my__pb2.FileRequest.SerializeToString,
            my__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Case2(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/proto15test.FileTransferService/Case2',
            my__pb2.FileRequest.SerializeToString,
            my__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Case3(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto15test.FileTransferService/Case3',
            my__pb2.FileRequest.SerializeToString,
            my__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Case4(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/proto15test.FileTransferService/Case4',
            my__pb2.FileRequest.SerializeToString,
            my__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
