# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='my.proto',
  package='proto15test',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08my.proto\x12\x0bproto15test\"U\n\x0b\x46ileRequest\x12\x0f\n\x07image_1\x18\x01 \x01(\x0c\x12\x0f\n\x07image_2\x18\x02 \x01(\x0c\x12\x11\n\tfilename1\x18\x03 \x01(\t\x12\x11\n\tfilename2\x18\x04 \x01(\t\"\x1f\n\x0c\x46ileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x95\x02\n\x13\x46ileTransferService\x12<\n\x05\x43\x61se1\x12\x18.proto15test.FileRequest\x1a\x19.proto15test.FileResponse\x12>\n\x05\x43\x61se2\x12\x18.proto15test.FileRequest\x1a\x19.proto15test.FileResponse(\x01\x12>\n\x05\x43\x61se3\x12\x18.proto15test.FileRequest\x1a\x19.proto15test.FileResponse0\x01\x12@\n\x05\x43\x61se4\x12\x18.proto15test.FileRequest\x1a\x19.proto15test.FileResponse(\x01\x30\x01\x62\x06proto3'
)




_FILEREQUEST = _descriptor.Descriptor(
  name='FileRequest',
  full_name='proto15test.FileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_1', full_name='proto15test.FileRequest.image_1', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_2', full_name='proto15test.FileRequest.image_2', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filename1', full_name='proto15test.FileRequest.filename1', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filename2', full_name='proto15test.FileRequest.filename2', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=110,
)


_FILERESPONSE = _descriptor.Descriptor(
  name='FileResponse',
  full_name='proto15test.FileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='proto15test.FileResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['FileRequest'] = _FILEREQUEST
DESCRIPTOR.message_types_by_name['FileResponse'] = _FILERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileRequest = _reflection.GeneratedProtocolMessageType('FileRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILEREQUEST,
  '__module__' : 'my_pb2'
  # @@protoc_insertion_point(class_scope:proto15test.FileRequest)
  })
_sym_db.RegisterMessage(FileRequest)

FileResponse = _reflection.GeneratedProtocolMessageType('FileResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILERESPONSE,
  '__module__' : 'my_pb2'
  # @@protoc_insertion_point(class_scope:proto15test.FileResponse)
  })
_sym_db.RegisterMessage(FileResponse)



_FILETRANSFERSERVICE = _descriptor.ServiceDescriptor(
  name='FileTransferService',
  full_name='proto15test.FileTransferService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=146,
  serialized_end=423,
  methods=[
  _descriptor.MethodDescriptor(
    name='Case1',
    full_name='proto15test.FileTransferService.Case1',
    index=0,
    containing_service=None,
    input_type=_FILEREQUEST,
    output_type=_FILERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Case2',
    full_name='proto15test.FileTransferService.Case2',
    index=1,
    containing_service=None,
    input_type=_FILEREQUEST,
    output_type=_FILERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Case3',
    full_name='proto15test.FileTransferService.Case3',
    index=2,
    containing_service=None,
    input_type=_FILEREQUEST,
    output_type=_FILERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Case4',
    full_name='proto15test.FileTransferService.Case4',
    index=3,
    containing_service=None,
    input_type=_FILEREQUEST,
    output_type=_FILERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILETRANSFERSERVICE)

DESCRIPTOR.services_by_name['FileTransferService'] = _FILETRANSFERSERVICE

# @@protoc_insertion_point(module_scope)
